#pragma once

// Private support for the map_tests contract runner: synthetic TED fixture
// builders and helpers shared by the decode and reference test groups.

#include "eawr/assets/map.hpp"

#include <algorithm>
#include <array>
#include <bit>
#include <chrono>
#include <cmath>
#include <cstddef>
#include <cstdint>
#include <filesystem>
#include <fstream>
#include <iostream>
#include <limits>
#include <optional>
#include <set>
#include <string>
#include <string_view>
#include <vector>

namespace eawr::tests::map_contracts {
extern int failures;
void expect(bool condition, const char* message);
void u8(std::vector<std::byte>& out, std::uint8_t value);
void u16(std::vector<std::byte>& out, std::uint16_t value);
void u32(std::vector<std::byte>& out, std::uint32_t value);
void f32(std::vector<std::byte>& out, float value);
void add(std::vector<std::byte>& out, const std::vector<std::byte>& value);
std::vector<std::byte> chunk(std::uint32_t id, const std::vector<std::byte>& payload, bool group = false);
void mini(std::vector<std::byte>& out, std::uint8_t id, const std::vector<std::byte>& payload);
std::vector<std::byte> integer(std::uint32_t value);
std::vector<std::byte> real(float value);
std::vector<std::byte> vector3(float x, float y, float z);
std::vector<std::byte> narrow(std::string_view text);
std::vector<std::byte> wide(std::u16string_view text);
std::vector<std::byte> file_from(const std::vector<std::byte>& root, const std::vector<std::byte>& body);

// A placement record body.  The minis are written in the order given, so a
// test can shuffle them.
struct Record final {
    std::string type{"Fixture_Prop"};
    std::optional<std::array<float, 3>> orientation{std::array<float, 3>{0.0F, 0.0F, 90.0F}};
    bool shuffled{};
};

std::vector<std::byte> placement_body(const Record& record, std::uint32_t serial);
std::vector<std::byte> object_record(const std::vector<std::byte>& body);

// Original synthetic TED fixture options.  Every value is invented here, not
// copied from an installed map or generated by production code.
struct Fixture final {
    std::uint32_t kind{1};
    bool include_main{true};
    bool land_groups{true};         // write 1/257, 1/266, 1/267
    bool patch_group{true};         // write 1/267
    std::uint32_t width{2};
    std::uint32_t height{3};
    std::uint32_t cell_count{6};
    std::vector<std::int16_t> heights{-512, -1, 0, 1, 512, 2048};
    std::vector<std::uint8_t> slots{0, 1, 2, 3, 4, 5};
    std::vector<std::uint8_t> intensities{0, 51, 102, 153, 204, 255};
    std::size_t materials{6};
    int plane_delta{};              // -1 one byte short, +1 one byte long
    bool legacy_plane{};            // write 1/257/1 instead of 1/257/5
    bool water{true};
    bool volumes{true};
    bool old_volumes{};             // older 1/259 form with scalar and standalone vector minis
    std::vector<std::byte> volume_stream; // optional exact 1/259 mini stream
    bool environment_extra{true};   // write the optional 1/256/8
    std::vector<std::vector<std::byte>> environment_records; // optional synthetic 1/256/4/6 streams
    bool unknown_chunk{};
    bool preview{};
    bool waves{};                   // write a nested 1/257/9 wave group
    std::vector<std::byte> extra_root; // appended raw root minis
    bool new_header{};              // 0x0B before 0x08, then 0x09, 0x10, 0x11, 0x12
    std::vector<Record> records{Record{}};
    std::vector<std::vector<std::byte>> raw_records; // appended pre-built 1100 records
};

std::vector<std::byte> ted(const Fixture& fixture);
Fixture space_fixture();
eawr::assets::ObjectTypeRef type_ref(const std::string& id, const char* model = nullptr);
eawr::assets::AssetProbe probe_over(std::set<std::string> present);
eawr::assets::Source source(std::size_t size);
const eawr::assets::ObjectTypeCatalog& fixture_catalog();
eawr::core::Result<eawr::assets::Map> load(const Fixture& fixture,
                                           const eawr::assets::ObjectTypeCatalog& catalog = fixture_catalog());
eawr::core::Result<eawr::assets::Map> load_bytes(const std::vector<std::byte>& bytes);
std::size_t count_issue(const eawr::assets::Map& map, eawr::assets::MapIssue kind);
const eawr::assets::MapNotice* find_issue(const eawr::assets::Map& map, eawr::assets::MapIssue kind);
const eawr::assets::RawChunk* raw_terrain_plane(const eawr::assets::Map& map, std::uint32_t leaf = 5);
bool near(float left, float right);

// map_decode_tests.cpp
void terrain_values();
void terrain_failures();
void kind_structure();
void framing();
void header_views();
void oversize_record();

// map_reference_tests.cpp
void placements();
void resolution();
void environment_reference_ledger();
} // namespace eawr::tests::map_contracts
