"""Wholly original synthetic placement fixture for the P1-11 populated map mode.

Every byte here is generated by this module from invented values: a flat land
TED map with seven placements, an XML catalog naming five invented objects,
three box-shaped ALO models and four solid-colour DDS textures. Nothing is
copied from, derived from or shaped like an installed asset beyond the public
chunk layouts the loaders document. Object and file names all carry an
``EAWR_SCENE`` / ``eawr_scene`` prefix so a fixture value can never be mistaken
for original-game content.

``write_fixture_root(root)`` materialises ``root/GameData/Data`` so the viewer
can be run with ``--eawr-game-root root``; ``EXPECTED`` is what the populated
map mode must report, derived from the fixture's own definitions.
"""

from __future__ import annotations

import pathlib
import struct
import zlib

MAP_LOGICAL_PATH = "data/art/maps/eawr_scene_synthetic.ted"

# Terrain: flat, 33 x 25 samples at 20 source units -> 640 x 480 units.
TERRAIN_WIDTH = 33
TERRAIN_HEIGHT = 25

# name -> (model file, scale factor or None)
OBJECTS = {
    "EAWR_SCENE_TOWER": ("eawr_scene_tower.alo", "1.5"),
    "EAWR_SCENE_DEPOT": ("eawr_scene_depot.alo", None),
    "EAWR_SCENE_BEACON": ("eawr_scene_beacon.alo", None),
    "EAWR_SCENE_MARKER": ("eawr_scene_marker.alo", None),
}

# (object id, source position, (roll, pitch, yaw) degrees)
PLACEMENTS = [
    ("EAWR_SCENE_TOWER", (160.0, 120.0, 0.0), (0.0, 0.0, 0.0)),
    ("EAWR_SCENE_TOWER", (480.0, 360.0, 0.0), (0.0, 0.0, 45.0)),
    ("EAWR_SCENE_DEPOT", (480.0, 120.0, 0.0), (0.0, 0.0, 90.0)),
    ("EAWR_SCENE_BEACON", (160.0, 360.0, 0.0), (0.0, 0.0, 0.0)),
    ("EAWR_SCENE_MARKER", (320.0, 240.0, 0.0), (0.0, 0.0, 0.0)),
    ("EAWR_SCENE_UNLISTED", (320.0, 100.0, 0.0), (0.0, 0.0, 0.0)),
    ("EAWR_SCENE_TOWER", (320.0, 380.0, 0.0), (10.0, 0.0, 0.0)),
]

# model file -> list of (shader, texture name, box half-extent x, y, height)
MODELS = {
    "eawr_scene_tower.alo": [("MeshGloss.fx", "eawr_scene_red.tga", 20.0, 20.0, 60.0)],
    "eawr_scene_depot.alo": [("BatchMeshGloss.fx", "eawr_scene_blue.tga", 40.0, 16.0, 20.0)],
    "eawr_scene_beacon.alo": [
        ("MeshAlpha.fx", "eawr_scene_yellow.tga", 18.0, 18.0, 30.0),
        ("MeshShadowVolume.fx", "", 18.0, 18.0, 30.0),
    ],
    "eawr_scene_marker.alo": [("MeshSolidColor.fx", "", 10.0, 10.0, 10.0)],
}

# texture file -> RGBA
TEXTURES = {
    "eawr_scene_red.dds": (230, 30, 30, 255),
    "eawr_scene_blue.dds": (30, 60, 230, 255),
    "eawr_scene_yellow.dds": (240, 220, 20, 220),
    "eawr_scene_ground.dds": (30, 60, 30, 255),
}

EXPECTED = {
    "placements": 7,
    # towers 0 and 1, the depot: every surface supported and resolved.
    "resolved": 3,
    # plus the beacon, whose shadow-volume surface is unsupported.
    "drawable": 4,
    "unresolved": 4,
    "by_cause": {
        "shader_unsupported": 2,  # beacon (shadow volume) and marker (solid colour)
        "crc_missing": 1,
        "orientation_three_axis": 1,
    },
    "scene_assets": 4,
    "instances": 4,
    "surfaces_uploaded": 3,
}


def type_crc(name: str) -> int:
    """The documented TED type CRC: CRC-32 of the upper-cased object id."""
    return zlib.crc32(name.upper().encode("ascii")) & 0xFFFFFFFF


# --- binary helpers -----------------------------------------------------------

def _chunk(identifier: int, payload: bytes, group: bool = False) -> bytes:
    size = len(payload) | (0x80000000 if group else 0)
    return struct.pack("<II", identifier, size) + payload


def _mini(identifier: int, payload: bytes) -> bytes:
    assert len(payload) < 256
    return struct.pack("<BB", identifier, len(payload)) + payload


def _cstring(value: str) -> bytes:
    return value.encode("ascii") + b"\0"


# --- TED ------------------------------------------------------------------------

def ted_bytes(placements=None) -> bytes:
    """The synthetic map; ``placements`` replaces ``PLACEMENTS`` for callers
    that need a different object list on the same flat terrain."""
    root = _mini(0, struct.pack("<I", 0x0201)) + _mini(1, struct.pack("<I", 1))
    header = (_mini(0, struct.pack("<I", TERRAIN_WIDTH)) + _mini(1, struct.pack("<I", TERRAIN_HEIGHT))
              + _mini(4, struct.pack("<I", TERRAIN_WIDTH * TERRAIN_HEIGHT)) + _mini(5, struct.pack("<I", 1)))
    material = _chunk(3, _mini(0x0C, _cstring("eawr_scene_ground.tga")))
    plane = struct.pack("<hBB", 0, 0, 255) * (TERRAIN_WIDTH * TERRAIN_HEIGHT)
    terrain = _chunk(0, header) + _chunk(2, material, True) + _chunk(5, plane)
    objects = b""
    for serial, (name, position, orientation) in enumerate(PLACEMENTS if placements is None else placements,
                                                            start=500):
        minis = (_mini(0, struct.pack("<I", serial)) + _mini(1, struct.pack("<I", type_crc(name)))
                 + _mini(4, struct.pack("<3f", *position)) + _mini(5, struct.pack("<3f", *orientation)))
        record = _chunk(1113, _chunk(1200, minis), True)
        objects += _chunk(1100, record, True)
    main = (_chunk(256, b"", True) + _chunk(257, terrain, True) + _chunk(266, plane)
            + _chunk(267, b"", True) + _chunk(258, _chunk(1, objects, True), True))
    return struct.pack("<II", 0, len(root)) + root + _chunk(1, main, True)


# --- ALO ------------------------------------------------------------------------

def _box(half_x: float, half_y: float, height: float):
    """A closed box standing on z=0, with each face emitted in both windings so
    no culling convention can hide it."""
    corners = {
        "-x": [(-half_x, -half_y, 0), (-half_x, half_y, 0), (-half_x, half_y, height), (-half_x, -half_y, height)],
        "+x": [(half_x, -half_y, 0), (half_x, -half_y, height), (half_x, half_y, height), (half_x, half_y, 0)],
        "-y": [(-half_x, -half_y, 0), (-half_x, -half_y, height), (half_x, -half_y, height), (half_x, -half_y, 0)],
        "+y": [(-half_x, half_y, 0), (half_x, half_y, 0), (half_x, half_y, height), (-half_x, half_y, height)],
        "-z": [(-half_x, -half_y, 0), (half_x, -half_y, 0), (half_x, half_y, 0), (-half_x, half_y, 0)],
        "+z": [(-half_x, -half_y, height), (-half_x, half_y, height), (half_x, half_y, height), (half_x, -half_y, height)],
    }
    normals = {"-x": (-1, 0, 0), "+x": (1, 0, 0), "-y": (0, -1, 0), "+y": (0, 1, 0), "-z": (0, 0, -1), "+z": (0, 0, 1)}
    uvs = [(0.0, 0.0), (0.0, 1.0), (1.0, 1.0), (1.0, 0.0)]
    vertices = []
    indices = []
    for face, points in corners.items():
        base = len(vertices)
        for point, uv in zip(points, uvs):
            vertices.append((point, normals[face], uv))
        indices += [base, base + 1, base + 2, base, base + 2, base + 3]
        indices += [base, base + 2, base + 1, base, base + 3, base + 2]
    return vertices, indices


def _vertex(position, normal, uv) -> bytes:
    data = struct.pack("<3f", *position) + struct.pack("<3f", *normal)
    data += struct.pack("<2f", *uv) + struct.pack("<6f", 0, 0, 0, 0, 0, 0)  # four texcoords
    data += struct.pack("<3f", 1, 0, 0) + struct.pack("<3f", 0, 1, 0)       # tangent, binormal
    data += struct.pack("<4f", 1, 1, 1, 1) + struct.pack("<4f", 0, 0, 0, 0)  # colour, unused
    data += struct.pack("<4I", 0, 0, 0, 0) + struct.pack("<4f", 1, 0, 0, 0)  # bone indices, weights
    assert len(data) == 144
    return data


def alo_bytes(surfaces) -> bytes:
    bone_data = struct.pack("<iI", -1, 1) + struct.pack("<12f", 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0)
    bone = _chunk(0x202, _chunk(0x203, _cstring("Root")) + _chunk(0x205, bone_data), True)
    skeleton = _chunk(0x200, _chunk(0x201, struct.pack("<I", 1)) + bone, True)
    meshes = b""
    for index, (shader, texture, half_x, half_y, height) in enumerate(surfaces):
        vertices, indices = _box(half_x, half_y, height)
        parameters = _chunk(0x10101, _cstring(shader))
        if texture:
            parameters += _chunk(0x10105, _mini(1, _cstring("BaseTexture")) + _mini(2, _cstring(texture)))
        geometry = (_chunk(0x10001, struct.pack("<II", len(vertices), len(indices) // 3))
                    + _chunk(0x10002, _cstring("alD3dVertNU2"))
                    + _chunk(0x10007, b"".join(_vertex(*vertex) for vertex in vertices))
                    + _chunk(0x10004, struct.pack(f"<{len(indices)}H", *indices)))
        info = struct.pack("<I3f3fIII", 1, -half_x, -half_y, 0.0, half_x, half_y, height, 0, 0, 0)
        mesh = (_chunk(0x401, _cstring(f"Box{index}")) + _chunk(0x402, info)
                + _chunk(0x10100, parameters, True) + _chunk(0x10000, geometry, True))
        meshes += _chunk(0x400, mesh, True)
    connections = _chunk(0x601, _mini(1, struct.pack("<I", len(surfaces))) + _mini(4, struct.pack("<I", 0)))
    for index in range(len(surfaces)):
        connections += _chunk(0x602, _mini(2, struct.pack("<I", index)) + _mini(3, struct.pack("<I", 0)))
    return skeleton + meshes + _chunk(0x600, connections, True)


# --- DDS ------------------------------------------------------------------------

def dds_bytes(rgba) -> bytes:
    width = height = 4
    header = struct.pack("<4sIIIIIII", b"DDS ", 124, 0x100F, height, width, width * 4, 0, 1)
    header += b"\0" * 44
    header += struct.pack("<IIIIIIII", 32, 0x41, 0, 32, 0x000000FF, 0x0000FF00, 0x00FF0000, 0xFF000000)
    header += struct.pack("<IIIII", 0x1000, 0, 0, 0, 0)
    assert len(header) == 128
    return header + bytes(rgba) * (width * height)


# --- XML ------------------------------------------------------------------------

def objects_xml() -> str:
    lines = ['<?xml version="1.0" encoding="utf-8"?>', "<GroundStructures>"]
    for name, (model, scale) in OBJECTS.items():
        lines.append(f'  <GroundBuildable Name="{name}">')
        lines.append(f"    <Land_Model_Name>{model}</Land_Model_Name>")
        if scale is not None:
            lines.append(f"    <Scale_Factor>{scale}</Scale_Factor>")
        lines.append("  </GroundBuildable>")
    lines.append("</GroundStructures>")
    return "\n".join(lines) + "\n"


def write_fixture_root(root: pathlib.Path) -> pathlib.Path:
    data = root / "GameData" / "Data"
    (data / "Art" / "Maps").mkdir(parents=True, exist_ok=True)
    (data / "Art" / "Models").mkdir(parents=True, exist_ok=True)
    (data / "Art" / "Textures").mkdir(parents=True, exist_ok=True)
    (data / "XML").mkdir(parents=True, exist_ok=True)
    (data / "Art" / "Maps" / "EAWR_SCENE_SYNTHETIC.TED").write_bytes(ted_bytes())
    for name, surfaces in MODELS.items():
        (data / "Art" / "Models" / name).write_bytes(alo_bytes(surfaces))
    for name, rgba in TEXTURES.items():
        (data / "Art" / "Textures" / name).write_bytes(dds_bytes(rgba))
    xml = data / "XML"
    (xml / "GameObjectFiles.xml").write_text(
        "<Game_Object_Files><File>eawr_scene_objects.xml</File></Game_Object_Files>\n", encoding="utf-8")
    (xml / "HardpointDataFiles.xml").write_text("<Hard_Point_Files></Hard_Point_Files>\n", encoding="utf-8")
    (xml / "FactionFiles.xml").write_text("<Faction_Files></Faction_Files>\n", encoding="utf-8")
    (xml / "CampaignFiles.xml").write_text("<Campaign_Files></Campaign_Files>\n", encoding="utf-8")
    (xml / "SFXEventFiles.xml").write_text("<SFXEvent_Files></SFXEvent_Files>\n", encoding="utf-8")
    (xml / "eawr_scene_objects.xml").write_text(objects_xml(), encoding="utf-8")
    # The accepted manifest contract records a declared-but-missing archive
    # while the loose layer stays fully enumerable.
    (data / "MegaFiles.xml").write_text("<Mega_Files><File>Missing.meg</File></Mega_Files>", encoding="utf-8")
    return root
