#!/usr/bin/env python3
"""Require exact per-target replay evidence and report the first mismatch."""

from __future__ import annotations

import argparse
import json
import pathlib
import re
import sys

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent / "common"))
import eawr_evidence_io  # noqa: E402


DEFAULT_TARGETS = (
    "windows-msvc",
    "windows-clang",
    "linux-x64-gcc",
    "linux-x64-clang",
    "linux-arm64-gcc",
)
WORKERS = (1, 2, 4)
ROW = re.compile(r"([1-9][0-9]*),([0-9a-f]{64})\Z")


def read_rows(path: pathlib.Path) -> list[tuple[int, str]]:
    try:
        raw = eawr_evidence_io.read_bytes(path)
    except OSError as error:
        raise ValueError(f"missing required result {path}: {error}") from error
    if raw.startswith(b"\xef\xbb\xbf") or b"\r" in raw or not raw.endswith(b"\n"):
        raise ValueError(f"{path}: expected UTF-8 without BOM and LF-only lines")
    try:
        lines = raw.decode("utf-8").splitlines()
    except UnicodeDecodeError as error:
        raise ValueError(f"{path}: invalid UTF-8: {error}") from error
    if not lines or lines[0] != "tick,sha256":
        raise ValueError(f"{path}: missing exact tick,sha256 header")
    rows: list[tuple[int, str]] = []
    for line_number, line in enumerate(lines[1:], 2):
        match = ROW.fullmatch(line)
        if not match:
            raise ValueError(f"{path}:{line_number}: malformed hash row")
        tick = int(match.group(1))
        if tick != len(rows) + 1:
            raise ValueError(
                f"{path}:{line_number}: first missing/out-of-order tick is {len(rows) + 1}"
            )
        rows.append((tick, match.group(2)))
    return rows


def compare(
    baseline_name: str,
    baseline: list[tuple[int, str]],
    candidate_name: str,
    candidate: list[tuple[int, str]],
) -> None:
    shared = min(len(baseline), len(candidate))
    for index in range(shared):
        if baseline[index] != candidate[index]:
            tick = min(baseline[index][0], candidate[index][0])
            raise ValueError(
                f"first divergent tick {tick}: {baseline_name}={baseline[index][1]} "
                f"{candidate_name}={candidate[index][1]}"
            )
    if len(baseline) != len(candidate):
        raise ValueError(
            f"first missing tick {shared + 1}: {baseline_name} has {len(baseline)} rows, "
            f"{candidate_name} has {len(candidate)} rows"
        )


def required_bytes(path: pathlib.Path) -> bytes:
    try:
        data = eawr_evidence_io.read_bytes(path)
    except OSError as error:
        raise ValueError(f"missing required result {path}: {error}") from error
    if not data or b"\r" in data or data.startswith(b"\xef\xbb\xbf") or not data.endswith(b"\n"):
        raise ValueError(f"{path}: expected nonempty LF-only evidence without BOM")
    return data


def compare_bundle(evidence: pathlib.Path, fixtures: pathlib.Path, targets: tuple[str, ...]) -> None:
    # CSV goldens are independently generated by generate_tactical_fixture.py.
    for kind in ("hashes", "events", "snapshots"):
        expected = required_bytes(fixtures / f"tactical-v2.{kind}.csv")
        for target in targets:
            for workers in WORKERS:
                path = evidence / f"replay-evidence-{target}" / f"tactical-v2-workers-{workers}.{kind}.csv"
                actual = required_bytes(path)
                if actual != expected:
                    raise ValueError(f"{path}: tactical-v2 {kind} differs from independent fixture")
    baseline: dict[str, bytes] = {}
    for target in targets:
        for workers in WORKERS:
            directory = evidence / f"replay-evidence-{target}"
            for kind in ("hashes.csv", "snapshots.csv", "census.json"):
                path = directory / f"skirmish-workers-{workers}.{kind}"
                actual = required_bytes(path)
                if kind == "census.json":
                    try:
                        census = json.loads(actual)
                        state = census["tick_zero"]["state_sha256"]
                        snapshot = census["tick_zero"]["snapshot_sha256"]
                    except (ValueError, KeyError, TypeError) as error:
                        raise ValueError(f"{path}: invalid tick-zero census: {error}") from error
                    # Frozen EAWRTST setup hash, independently checked by the skirmish CLI test.
                    if state != "9c52d81b8736b411c16cbcb68af561e5d8106cd108946a888a946c162b240b6e":
                        raise ValueError(f"{path}: skirmish tick-zero state differs from frozen setup")
                    rows = required_bytes(directory / f"skirmish-workers-{workers}.snapshots.csv").splitlines()
                    if len(rows) < 2 or rows[1] != f"0,{snapshot}".encode():
                        raise ValueError(f"{path}: skirmish tick-zero snapshot is missing or inconsistent")
                if kind not in baseline:
                    baseline[kind] = actual
                elif actual != baseline[kind]:
                    raise ValueError(f"{path}: skirmish {kind} differs across targets/workers")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--evidence-root", type=pathlib.Path, required=True)
    parser.add_argument(
        "--audit",
        type=pathlib.Path,
        required=True,
        help="frozen independent original-v1 audit JSON",
    )
    parser.add_argument(
        "--target",
        action="append",
        dest="targets",
        help="expected target name; repeat to override the five CI defaults",
    )
    parser.add_argument("--tactical-fixtures", type=pathlib.Path,
                        help="also require tactical-v2 bundles and skirmish tick-zero evidence")
    args = parser.parse_args()
    targets = tuple(args.targets) if args.targets else DEFAULT_TARGETS
    if len(targets) != len(set(targets)):
        print("duplicate target names are not permitted", file=sys.stderr)
        return 2

    try:
        try:
            audit = json.loads(args.audit.read_text(encoding="utf-8"))
            expected = [
                (int(item["completed_tick"]), str(item["state_sha256"]))
                for item in audit["ticks"]
            ]
        except (OSError, UnicodeError, json.JSONDecodeError, KeyError, TypeError, ValueError) as error:
            raise ValueError(f"could not read frozen audit {args.audit}: {error}") from error
        if not expected or any(tick != index for index, (tick, _) in enumerate(expected, 1)):
            raise ValueError(f"{args.audit}: frozen audit must contain contiguous positive ticks")
        for tick, digest in expected:
            if ROW.fullmatch(f"{tick},{digest}") is None:
                raise ValueError(f"{args.audit}: invalid frozen hash at tick {tick}")

        for target in targets:
            directory = args.evidence_root / f"replay-evidence-{target}"
            identity = directory / "target.txt"
            try:
                recorded_target = eawr_evidence_io.read_text(identity).strip()
            except OSError as error:
                raise ValueError(f"missing target identity {identity}: {error}") from error
            if recorded_target != target:
                raise ValueError(
                    f"target identity mismatch in {identity}: expected {target!r}, "
                    f"found {recorded_target!r}"
                )
            for workers in WORKERS:
                name = f"{target}/workers-{workers}"
                rows = read_rows(directory / f"workers-{workers}.csv")
                compare("independent fixture audit", expected, name, rows)
        if args.tactical_fixtures is not None:
            compare_bundle(args.evidence_root, args.tactical_fixtures, targets)
    except ValueError as error:
        print(error, file=sys.stderr)
        return 1
    print(
        f"replay evidence agrees across {len(targets)} named targets, "
        f"{len(WORKERS)} worker counts, and {len(expected)} frozen ticks"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
